PharmQuest/BE

- src/main/java/com/pharmquest/pharmquest/medicine/domain/Medicine.java
- src/main/java/com/pharmquest/pharmquest/mypage/domain/MedicineScrap.java
- src/main/java/com/pharmquest/pharmquest/mypage/domain/PharmacyScrap.java
- src/main/java/com/pharmquest/pharmquest/mypage/domain/PostScrap.java
- src/main/java/com/pharmquest/pharmquest/mypage/domain/SupplementScrap.java
- src/main/java/com/pharmquest/pharmquest/pharmacy/domain/Pharmacy.java
- src/main/java/com/pharmquest/pharmquest/post/domain/Post.java
- src/main/java/com/pharmquest/pharmquest/supplements/domain/Supplements.java
- src/main/java/com/pharmquest/pharmquest/user/domain/User.java
- src/main/resources/application.properties
- src/main/resources/application.yml.example
Resolved #3 
- 다른 테이블 연결 기초 로직 추가 mysql 테이블 생성
- example.파일 사용해서 본인 name,pw 입력 및 mysql에 해당 db 생성후 실행
> feat : 다른 테이블 연결 기초 로직 추가 mysql 테이블 생성

- build.gradle
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/ApiResponse.java
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/BaseCode.java
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/BaseErrorCode.java
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/ErrorReasonDTO.java
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/ReasonDTO.java
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/code/status/SuccessStatus.java
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/exception/ExceptionAdvice.java
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/exception/GeneralException.java
- src/main/java/com/pharmquest/pharmquest/common/apiPayload/exception/handler/CommonExceptionHandler.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/domain/Medicine.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/MedicineScrap.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PharmacyScrap.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PostScrap.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/SupplementScrap.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/domain/Pharmacy.java
- src/main/java/com/pharmquest/pharmquest/domain/post/domain/Post.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/domain/Supplements.java
- src/main/java/com/pharmquest/pharmquest/domain/user/domain/User.java
Resolved #10 
- 도메인 패키지와 공통(글로벌) 패키지를 분리
- 공통 응답 처리 코드 작성 
- 7주차의 TempHandler -> CommonExceptionHandler 명칭 변경
> feat : 공통 응답 처리 작성

- build.gradle
- src/main/java/com/pharmquest/pharmquest/medicine/config/SwaggerConfig.java
- src/main/java/com/pharmquest/pharmquest/medicine/config/WebClientConfig.java
- src/main/java/com/pharmquest/pharmquest/medicine/controller/MedicineController.java
- src/main/java/com/pharmquest/pharmquest/medicine/dto/MedicineResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/medicine/repository/MedicineRepository.java
- src/main/java/com/pharmquest/pharmquest/medicine/service/MedicineService.java
- src/main/java/com/pharmquest/pharmquest/medicine/service/MedicineServiceImpl.java
Resolved #11 
- 내용
fdaOpenAPI를 연결하여 전체 filed를 확인 후 필요한 정보만 조정
해당 정보 불러와지는 것 확인
- img제공이 없는 문제가 있음 -> 현재 생각은 약의 코드로 찾는 방법 생각 (잘 찾아질지는 미지수)
- 번역하는 방식도 찾아봐야함, 번역까지 되고 난 이후에 세부 api 구현 예정
- 페이지 처리도 추후 예정
- 2명 이상 확인하면 머지하겠습니다
- 현재는 GET 방식, 실제 mysql DB 연결 안된 상황
> [FEAT] medicine OPENAPI 정보 연결

- build.gradle
- src/main/java/com/pharmquest/pharmquest/PharmquestApplication.java
- src/main/java/com/pharmquest/pharmquest/domain/home/repository/HomePostRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/home/response/HomePostsResponse.java
- src/main/java/com/pharmquest/pharmquest/domain/home/service/HomePostService.java
- src/main/java/com/pharmquest/pharmquest/domain/home/web/controller/HomePostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/PostRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/PostRepositoryCustom.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/PostRepositoryImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/data/BaseEntity.java
- src/main/java/com/pharmquest/pharmquest/mypage/domain/PostScrap.java
Resolved #20 
- Post 도메인 계층으로 수정
- 스프링 버전 3.4.1 -> 3.3.7 수정 (스웨거 문제로 수정했습니다.)
> refactor: post 도메인 계층으로 수정

- src/main/resources/templates/index.html
- src/main/resources/templates/loginForm.html
> refactor: post 도메인 오류 해결

- src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PostScrap.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/PostCategory.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/ReportType.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/PostReport.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/scrap/PostScrapRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/specification/PostSpecification.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
Resolved #35 
- 제목, 내용 기반 게시글 검색 기능 구현(카테고리와 키워드로 필터링)
- 게시글 작성 시 임시로 userId 받도록 수정 
- 고려 사항이 키워드가 제목 OR 내용에 포함되어 있는지 여부, 카테고리, 나라 정도라 Specification을 사용하여 구현하였습니다. QueryDSL을 사용하여 리팩토링 하는게 좋을지 궁금합니다
> [Feat] 게시글 검색 기능 구현

- src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/SupplementScrap.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/PostReport.java
Resolved #35
- 마이페이지 Supplements  경로 수정
- 내용
> refactor: 파일 오류 수정

- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Resolved #42
- 내용
단일 정보의 전체 칼럼 및 정보 조회를 위해 추가했습니다 
- 내용
개발이 끝난 후에는 지울 예정입니다
> [FEAT]  : 단일 약 전체 정보 조회 (개발 확인용)

- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Resolved #47 
- repository 간소화하면서 service에 비즈니스 로직 추가 했습니다!
- 내용
> [상비약] 구조로직 

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Supplements.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/data/enums/Nation.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsScrap.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsScrapRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrapService.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrapServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsService.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementsScrapController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapResponseDTO.java
Resolved #38 - 1
- 영양제 스크랩 서비스 구현
> Feature/supplements/#38 - 영양제 스크랩 서비스 구현

- src/main/java/com/pharmquest/pharmquest/domain/mypage/domain/PostScrap.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostLikeConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostScrapConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/PostLike.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/PostReport.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/like/PostLikeRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/scrap/PostScrapRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/like/PostLikeService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/like/PostLikeServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/scrap/PostScrapService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/scrap/PostScrapServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Resolved #39 
- 게시글 좋아요 생성, 취소
- 게시글 스크랩 생성, 취소
- 아직 예외처리는 따로 진행하지 않았습니다.
> [Feat] 게시글 좋아요 생성, 취소 및 스크랩 생성, 취소 구현

- .github/workflows/dev_deploy.yml
Resolved #66
깃허브 액션 연결을 확인하기 위한 초안 코드입니다
- 내용
아직 다른 설정을 하지 않았기 때문에 깃허브액션 오류가 나는 것은 당연합니다 
이후 다른 설정을 추가할 계획입니다
- 내용
> feat : cicd 기초 코드 확인

- .github/workflows/dev_deploy.yml
> fix : 배포 build 오류 수정

- .github/workflows/dev_deploy.yml
> fix : 디버깅 코드 추가

- .github/workflows/dev_deploy.yml
> fix : dev_deploy.yml수정

- .github/workflows/dev_deploy.yml
> fix : 버전 변경

- build.gradle
> fix : 배포성공 이후 ec2 ip 실행 확인 안되는 문제

- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
Resolved #74
- 기존 코드에 경로가 service상에 적혀있어서 배포와 로컬의 경로 차이로 인한 문제가 있었습니다! 
경로를 yml에 등록해서 로컬에서는 로컬 경로, 배포에서는 배포 경로를 사용해 경로가 달라져도 둘 다 진행하는데 문제 없도록 변수처리 했습니다 
- 내용
> fix : 번역 json 경로 yml에 등록

- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
Resolved #76
- 내용  json경로 로컬,배포 모두 고려하여 같은 코드를 둘 다 사용할 수 있도록 했습니다
- 내용
> ref : 번역 서비스 json경로 로컬,배포 모두 고려

- .github/workflows/dev_deploy.yml
> fix : dev_deploy.yml작성

- .github/workflows/dev_deploy.yml
- build.gradle
- src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Resolved #78 
- 내용
배포 관련 dev.yml 수정 및 
우선 연결 로직 확인을 위해 전체 yml만 secret설정으로 진행
- 내용
> fix : 배포 관련 로직 수정

- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
> fix : medRepository 병합하며 생긴 오류 수정

- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/Medrepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
> ref : medRepository 수정

- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
Resolved #89 
- dev에서 main으로 머지가 진행될 경우 배포가 진행됩니다
- 지금까지처럼 feat->dev브런치를 통해 지속적으로 개발을 진행하고
dev에서 문제가 없으면 ->main으로 배포 과정을 진행해 최종 배포를 진행예정입니다
> ref : dev->main test

- src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Resolved #93 
- 리스트 카테고리별 10개씩 필요 보여주는 처리입니다
- 현재 연산량이 많아서 필터링, 찾기, 이미지 매칭등 속도가 느립니다 향후 개선 예정입니다
- 기타와 전체는 아직 처리상 에러가 있어서 현재 카테고리 종류만 확인 가능합니다 
- 카테고리의 경우 숫자로 매칭해서 구분했습니다
- 나중에 코드 리팩토링 할 생각입니다
- 국가가 아직 한국 api는 가져오지 않아 무조건 미국만 있어서 일단 하드코딩으로 미국 처리했습니다 추후 수정 예정
> [상비약] 리스트 조회

- .github/workflows/dev_deploy.yml
- src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/TranslationService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/Comment.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/PostCommentRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/like/PostLikeRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/like/PostLikeService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentRequestDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/user/data/User.java
Resolved #이슈번호
- 게시글 댓글, 상비약 리스트 조회 관련 작업들 배포에 반영하기 위해서 업데이트합니다
- 내용
> [배포] 게시글 댓글, 상비약 리스트 조회 업데이트 

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsCategory.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsService.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Resolved #102
- api 연동 관련 코드 패키지화 및 내부 구조 수정
- 내용
> refactor: api 관련 코드 패키지화 및 구조 수정

- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/report/PostReportRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/PostHandler.java
Resolved #108 
- 게시글 수정 삭제 구현
- 게시글 작성할 때 title, content null 불가능
- 에러 처리 수정
- PostDetailDTO 수정(본인이 작성한 게시글인지 체크 가능하도록 Boolean 값)
- title과 content에 null이 불가능하도록 service에서 처리했는데 워크북처럼 validation 처리하는 것이 좋을지
> [Feat] 게시글 수정 삭제 구현

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryKeyword.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementsScrapController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
Resolved #109 
- 연관된 영양제 로드
- jwtUtil 적용
- 풀 충돌 오류 해결
- 내용
> 연관된 영양제 로드 + jwtUtil 적용(풀 충돌 오류 해결)

- src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/config/WebClientConfig.java
Resolved #104
- 연산량 문제로 사용하는 데이터양이 적기 때문에 db로 저장후 db에서 조회를 실행하도록 수정했습니다!
- 카테고리별 딱 10개씩이 아니라 9~11개 정보를 가져왔습니다 이 부분은 추후 수정 예정
> [상비약] 단일정보, 리스트 조회 openAPI에서 db 연결

- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Naver/NaverShoppingServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementsScrapController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Resolved #116 
- 한국 영양제 정보 로드 (DB 수작업을 위한 로그문 추가)
- dailyMed 저장 정보 수정(null값을 받아올 시에 저장 X)
- 내용
> [Feat] 한국 영양제 정보 로드 및 dailyMed 저장 정보 수정

- src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsScrapRepository.java
Resolved #100
- 페이징 적용
- 카테고리 목록 추가
- 카테고리별 조회 기능 추가
> [Feat] 스크랩한 영양제 카테고리 기능 추가

- src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
Resolved #134 
- 마이페이지 부분 작업 후 머지할 때 오류 발생 😢 
- 이전 부분의 메서드와 새로운 메서드 간의 충돌로 인해 발생
- 해결✨
- getScrapSupplements 충돌
> [Fix] merge 후 발생한 오류 해결

- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/ReportType.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/PostReport.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/report/PostReportServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentRequestDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Resolved #125 
- 신고 타입 enum에 한국어 추가
- 게시글 상세정보에 나라 추가
- 내용
> [Refactor] 신고 타입 수정, 게시글 상세 정보 수정

- src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/OAuthLoginSuccessHandler.java
Resolved #138
- 로그인 성공시 redirect url 응답 방식 수정
- 내용
> [FEAT] 소셜 로그인 Redirect Url 응답 방식 수정

- build.gradle
- src/main/java/com/pharmquest/pharmquest/global/config/AwsS3Config.java
- src/main/java/com/pharmquest/pharmquest/global/data/S3File.java
- src/main/java/com/pharmquest/pharmquest/global/repository/S3FileRepository.java
- src/main/java/com/pharmquest/pharmquest/global/service/S3Service.java
- src/main/java/com/pharmquest/pharmquest/global/web/controller/S3Controller.java
Resolved #141
- 로컬 db에 등록된 사진 정보를 s3저장소 사용하도록 수정
- Post,광고배너에 사용 목적
- 우선 배포환경에 적용 확인
- post, 광고배너에서 적용되면
- 링크를 파일경로 서비스에 맞게 수정 및 이미지 이름 기준 변경 예정 (처음 연결작업 때 경로관련 오류는 배제할 목적)
> [Deploy] s3 사진 등록 조회 기본로직

- src/main/java/com/pharmquest/pharmquest/global/data/S3File.java
- src/main/java/com/pharmquest/pharmquest/global/repository/S3FileRepository.java
- src/main/java/com/pharmquest/pharmquest/global/service/S3Service.java
- src/main/java/com/pharmquest/pharmquest/global/web/controller/S3Controller.java
Resolved #141 
- 다양한 기능에서 활용을 위한 상세 주석 추가
- service코드 외에 repository,db,controller다 수정 필요 원하는 로직에
s3service코드안에 새롭게 메소드 추가해서 저장 로직을 수징한 코드 추가해야함
> [s3] 활용 목적 주석추가

- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/converter/MultipartJackson2HttpMessageConverter.java
- src/main/java/com/pharmquest/pharmquest/global/service/S3Service.java
Resolved #140 
- 게시글 작성기능 이미지 추가
- 게시글 상세보기 기능 이미지 추가
- 내용
> [Refactor] 게시글 작성기능 이미지 추가, 게시글 상세보기 기능 이미지 추가

- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
Resolved #145 
- 전체 리스트 ScrapCount기반 정렬
- 검색 결과 ScrapCount기반 정렬
- 내용
> [Refactor] 게시글 조회 시 인기순(스크랩순) 정렬

- src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
Resolved #154
- 나의 활동(게시글) 조회 기능 구현
- 내용
> [FEAT] 나의 활동(게시글) 기능 구현

- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/Comment.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/CommentLike.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/CommentReport.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/PostCommentRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/CommentLikeService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/CommentLikeServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/like/PostLikeServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/CommentHandler.java
Resolved #152
- 댓글 좋아요, 좋아요 취소 기능 구현
- 내용
> [Feature] 댓글 좋아요 기능

- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostLikeConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostReportConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostScrapConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/Comment.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/comment/PostCommentServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentRequestDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
Resolved #158 
- 댓글 수정 기능 구현
- 댓글 삭제 기능 구현. 데이터를 삭제하는 것이 아닌 is_deleted false->true로 변경
- 내용
> [Feature] 댓글 수정/삭제 기능 구현

- src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/PostCommentRepository.java
Resolved #155 
나의 활동(댓글) 조회 기능 구현
> [FEAT] 나의 활동 - 내가 작성한 댓글 조회 기능 구현

- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostRequestDTO.java
Resolved #163 
- 게시글 수정 기능에 이미지 추가
- 사진을 삭제하고 싶은건지 기존 사진을 유지하고 싶은건지 구분할 방법을 몰라서 deleteImage를 boolean 값으로 받는 것으로 구현하였습니다. 더 좋은 방법이 있는지 궁금합니다.
> [Refactor] 게시물 수정 기능 사진 추가

- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/ImageUtil.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/enums/PharmacyCountry.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/ErrorStatus.java
Resolved #151 
- 이미지 로직 분리
- 번역 기능 적용 후 조회 시간 길어지는 문제 발생
- 한 번에 조회하는 약국 수 조절 가능하도록 변경
- 국가 조건 Enum으로 변경
- 내용
> [Refactor] 약국 스크랩 기능 수정

- src/main/java/com/pharmquest/pharmquest/domain/user/repository/UserRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/user/service/UserService.java
- src/main/java/com/pharmquest/pharmquest/domain/user/service/UserServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/user/web/controller/UserController.java
- src/main/java/com/pharmquest/pharmquest/domain/user/web/dto/UserDTO.java
Resolved #169
- 유저 정보 반환 api 입니다.
- 내용
> [FEAT] 유저 정보 반환 기능 구현

- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
Resolved #175
- 증상 키워드에서 해당 정보를 가지고 있는 약들만 리스트 형태로 출력합니다
- 검색의 정확성 및 디테일한 내용은 수정해야합니다.
> feat : 상비약 카테고리, 증상 키워드 검색

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Resolved #177 
- 리스트 조회, 검색 조회 시 전체 이름에서 국가, 상품명 분리
- 내용
> [Refactor] 리스트, 검색 응답형태 수정

- src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
Resolved #180 
추가 응답값
- total_elements: 전체 아이템 수
- total_pages: 전체 페이지 수
- current_page: 현재 페이지 번호
- elements_per_page: 페이지당 아이템 수
> [Feat] 스크랩된 약국 조회 응답값 추가

- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyQueryService.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyQueryServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/dto/PharmacyResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/apiPayload/code/status/SuccessStatus.java
Resolved #182 
- 약국찾기 화면에서 조회한 약국이 스크랩되었는지 확인하는 api 구현
- 예외 처리할게 있을까나...?
> [Feat] 약국 저장 여부 확인

- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/CommentResponseDTO.java
Resolved #184 
- CommentDTO 정보 isLiked, isPostAuthor, isOwnComment 추가
- 내용
> [Refactor] CommentDTO 정보 추가

- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedicineScrapRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineScrapService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineScrapController.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/token/web/controller/TokenController.java
Resolved #190
- 스크랩한 상비약들을 조회합니다.
> [Feat] 상비약 스크랩 조회

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Enum/CategoryGroup.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsCategoryRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsService.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Resolved #187 
- 필터링 시 연관 키워드에 관한 결과 동시 제공
- 내용
> [REFACTOR] 필터링 시 연관 키워드에 관한 결과 동시 제공

- src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Resolved #119
- 검색 전체 수 반환, page시작 1부터
- 내용
> [상비약] 검색 전체 수 반환, page시작 1부터

- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
> ref : openAPI dto 수정

- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineListResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineOpenapiResponseDTO.java
> ref : dto 누락 추가

- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineListResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineOpenapiResponseDTO.java
> fix : dto누락 추가

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/DailyMed/DailyMedServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
Resolved #198 
- 토큰 문제 X
- scrapped 미반영 오류 수정
- dailymed연동 코드 수정
- 중복 코드 삭제
- 내용
> [Refactor] 유효하지 않은 토큰 에러 수정

- src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/data/enums/MedicineCategory.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineOpenapiResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Resolved #209 
- 상비약 조회 카테고리 한글, swagger 설명, db 리셋
- 내용
> Feature 상비약 조회 카테고리 한글, swagger 설명, db 리셋

- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/BestPost.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/bestPost/BestPostRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/like/PostLikeRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/like/PostLikeServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Resolved #196 
- 추천 수가 2개가 넘어갈 경우 베스트 인기글 테이블에 추가 (프론트 연동 후 추후 10개로 수정 예정)
- 베스트 인기글 중 랜덤으로 3개 선택
- 랜덤으로 가져올때 rand 퀴리문을 사용해서 가져오는 것으로 구현했는데 데이터가 많아질 경우 괜찮을지 궁금합니다. 
- 데이터의 개수를 count 해서 offset 방식으로 사용하는 경우도 있다고 하는데 식별자가 post_id라 적절하지 않은 듯하고🤔
> [Feat] 베스트 게시글 기능 구현

- src/main/java/com/pharmquest/pharmquest/domain/supplements/data/mapping/SupplementsScrap.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
Resolved #214 
- 동시성 처리 구현
- unique constraint key
- pessimistic lock
- supplement_scrap created_at 칼럼 삭제
- 내용
> [Bug] 영양제 스크랩 - 동시성 이슈

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Resolved #220 
- 영양제 검색 응답형태에서 중복된 형태 제거
- 일본 영양제 추가를 위한 데이터 정제 파트 수정
- 내용
> [Refactor] 영양제 검색 - 응답형태 제거 및 수정

- src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsScrapRepository.java
> [Feat] 스크랩된 영양제 코드 수정

- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
Resolved #227 
- 게시글 검색 기능 에러 처리 수정
- 내용
> [Refactor] 검색기능 에러 수정

- src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageService.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/controller/MyPageController.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsCategoryRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsScrapRepository.java
Resolved #225 
- 영양제 조회 부분 수정된대로 동일하게 변경하여 수정
- 응답 dto 추가
> [FEAT] 영양제 스크랩 조회 코드 수정

- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/data/mapping/Comment.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/PostCommentRepository.java
Resolved #233 
- 나의 활동 부분 페이지네이션이 정상 작동하지 않아 오류 수정
- 나의 활동 - 댓글 조회에서 삭제된 댓글까지 같이 조회되어 repository 쿼리문 수정
> [FIX] 마이페이지(나의 활동) 버그 수정

- src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/data/Medicine.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineController.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineDetailResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/MedicineResponseDTO.java
Resolved #226
- 상세 단일 정보, 기본 리스트,검색 리스트 모두 각 상비약의 스크랩 여부  추가 
- user정보로 부터 스크랩 여부를 확인하기 때문에 로그인을 해야지만 조회가 되는데 상비약 정보는 로그인을 하지 않아도 보이기 때문에 이부분 수정할 계획입니다
> feat : 상비약 정보 반환시 스크랩 여부 추가

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapResponseDTO.java
Resolved #242 
- 선택 카테고리 추가 반환(검색, 조회, 스크랩)
- 내용
> [Refactor] 선택 카테고리 추가 반환(검색, 조회, 스크랩)

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/config/JpaAuditingConfig.java
Resolved #247 
- 시간 null 저장 수정
- JpaAuditing 관련 config 파일 추가
> 시간 null 저장 수정 및 오타 수정

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/data/Advertisement.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementService.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/AdvertisementController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/controller/SupplementListController.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/AdResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsResponseDTO.java
Resolved #249 
- 영양제 반환 형태에 광고 객체 추가
- 내용
> [Refactor] 영양제 반환 시 광고 추가 반환 구현

- src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Resolved #255 
도메인구매
s5랑 연결 -> ip를 잘못 입력해서 엄청난 삽질을... 3시간 후에 알았습니다 ip번호가 잘못됐다는 것을... ㅠ
Spring Boot CORS 설정 추가
HTTPS 적용 HTTPS (SSL 인증서) 를 추가 
http로 접근해도 자동으로 https로 변경됨
- 현재는 백엔드에서만 도메인을 적용했기 때문에 cors 오류는 없지만 연동 과정에서 필요할 경우 
Spring Boot CORS 에다가 업데이트 하면 됩니다
> [DEPLOY] 도메인 연결

- src/main/java/com/pharmquest/pharmquest/domain/post/data/enums/Country.java
- src/main/java/com/pharmquest/pharmquest/domain/post/specification/PostSpecification.java
Resolved #258 
-  검색 기능에 country 전체 선택 추가
- 내용
> [Refactor] 검색 기능에 country 전체 선택 추가

- src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostService.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/bestPost/BestPostServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/controller/PostController.java
Resolved #260
- 베스트 게시글 로그인 없이 조회 수정
- 내용
> [Refactor] 베스트 게시글 로그인 없이 조회 수정

- src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Resolved #255
- ref : https 로 cors 에러 변경
- 내용
> ref : https 로 cors 에러 변경

- src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
Resolved #255
- [ref : swagger config https 반영 수정](https://github.com/PharmQuest/BE/commit/8c1bce68bd355495d8915c9f64238ea5690ce527)
- 내용
> ref : swagger config https 반영 수정

- src/main/java/com/pharmquest/pharmquest/domain/supplements/converter/SupplementsConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsCategoryRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementService.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Advertisement/AdvertisementServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/Supplements/SupplementsServiceImpl.java
Resolved #254 
- 카테고리 관련 N+1문제 해결
- 광고 반환 시 id 음수 처리 및 광고 표시 연산 수정
- 내용
> [Refactor] 카테고리 관련 N+1 문제 해결 및 광고 반환 수정

- src/main/java/com/pharmquest/pharmquest/domain/mypage/service/MyPageServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/ImageUtil.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/Pharmacy.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/repository/PharmacyRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyS3UpdateService.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
Resolved #262 
- 기본 이미지로 되어있는 약국에 대해 이미지 업데이트
- 매일 03시마다 업데이트
- 모든 약국들 중 기본 이미지로 되어있는 것들을 찾아내어, 그 약국들에 대해 google place api요청 후 이미지 업데이트
- 이미지 불러와진 약국에 대해서만 업데이트
> [Feat] 약국 이미지 주기적 업데이트

- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/Pharmacy.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsService.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyDetailsServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/web/controller/PharmacyController.java
Resolved #269 
- 이미지 url 길이로 인해 발생한 스크랩 오류 해결
- 스크랩 시 google place api 호출 횟수 2회 -> 1회 감소
- base64로 변환한 url이 mysql의 TEXT로 안 될 수도 있음. -> LONGTEXT로 변경
- 스크랩 시 photo_reference 반환하는 메서드를 파라미터별로 생성 -> google place api 호출 감소
> [Fix] 약국 스크랩 오류 해결 & api 호출 횟수 감소

- src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Resolved #255
- ref : 백엔드 서브도메인으로 변경
- 내용
> ref : 백엔드 서브도메인으로 변경

- src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
- src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
- src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
> ref : 서브 도메인 변경 config변경

- src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
- src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
- src/main/java/com/pharmquest/pharmquest/global/config/SwaggerConfig.java
Resolved #255
- 로컬환경에서 swagger가 api.도메인으로 자동 변경되는 문제 수정
- 내용
> ref : local cors 수정

- src/main/java/com/pharmquest/pharmquest/domain/supplements/repository/SupplementsRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/service/SupplementsScrap/SupplementsScrapServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/supplements/web/dto/SupplementsScrapResponseDTO.java
- src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
Resolved #277 
- 스크랩 응답시 selectedCategories 제거 (성능 강화)
- 스크랩 시 scrapCount만 업데이트하도록 하는 메서드 생성
- CorsConfig allowMethod PATCH 추가
- 내용
> 스크랩 관련 성능 강화 및 CorsConfig PATCH 추가

- src/main/java/com/pharmquest/pharmquest/domain/mypage/converter/MyPageConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/mypage/web/dto/MyPageResponseDTO.java
Resolved #279 
- 스크랩된 영양제 dto에 selectCategories를 추가하였습니다.
- 내용
> [FEAT] 스크랩된 영양제 응답 추가

- src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
Resolved #285 
- securityConfig setAllowedMethods에 PATCH 추가
- 이렇게 수정을 했을 때 해결이 될 지는 미지수
> bug: securityConfig 메서드 PATCH 추가

- src/main/java/com/pharmquest/pharmquest/global/config/CorsConfig.java
- src/main/java/com/pharmquest/pharmquest/global/config/SecurityConfig.java
Resolved #288 
- CorConfig.java main과 dev 동기화
- SecurityConfig.java main과 dev 동기화
- 내용
> ref: config 파일 main과 dev 동기화

- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/report/PostReportRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
- src/main/java/com/pharmquest/pharmquest/domain/post/web/dto/PostResponseDTO.java
Resolved #291 
- 게시글 상세 정보에 신고여부 추가
> [Refactor] 게시글 상세정보에 신고여부 추가

- src/main/java/com/pharmquest/pharmquest/domain/user/repository/UserRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/user/web/controller/TempLoginController.java
- src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/TempLoginHandler.java
Resolved #299 
- 임시 로그인
- 이름 작성 후 로그인
- name이 없다면 "Unknown"을 이름으로 로그인
- 현재 스프링 내부에서 동작하도록 했는데, 프론트랑 연동되게 하려면 어떻게 해야할까요... ✅ 
- 기존 소셜 로그인 로직을 이용 -> pw 필요 없게
> [Feat] 임시 로그인

- src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
Resolved #283 
- 카테고리별 게시글 조회 n+1 성능 개선
> [Refactor]

- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
> ref : 필터링 값 인식 변경

- src/main/java/com/pharmquest/pharmquest/global/apiPayload/exception/handler/TempLoginHandler.java
Resolved #310 
- 임시 로그인 시 담기는 유저 정보 변경
- email 값이 중복되지 않도록 설정되는 uuid의 일부만 저장하도록 변경
- 중복되지 않는 값이 uuid말고 있을까요
> [Refactor] 임시 로그인 유저 정보 변경

- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/MedicineServiceImpl.java
Resolved #314
- [ref : 페이지 네이션 수정](https://github.com/PharmQuest/BE/commit/12c7a31851db7ec64f76a1251174180f3f448974)
- 내용
> ref : 페이지 네이션 수정

- src/main/java/com/pharmquest/pharmquest/domain/post/data/Post.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentReportRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/post/PostRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
Resolved #325 
- N+1 문제 해결 중 데이터 반환 오류 발생 ->  해결 ✅ 
- 댓글 신고 기능 최적화
- Comment를 List로 처리하여 fetch join 할 때 데이터 중복이 발생 -> Set으로 변경
> [Fix] 게시글 상세조회 N+1 문제 해결 중 발생한 문제 해결

- src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/KoreanMedicineConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/data/MedicineCategoryMapper.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/KoreanMedicineRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/repository/MedRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/service/KoreanMedicineService.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/controller/MedicineTestController.java
- src/main/java/com/pharmquest/pharmquest/domain/medicine/web/dto/KoreanMedicineResponseDTO.java
> [상비약] 한국약 저장

- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/data/Pharmacy.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/repository/PharmacyRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandService.java
- src/main/java/com/pharmquest/pharmquest/domain/pharmacy/service/PharmacyCommandServiceImpl.java
Resolved #312
- 동시성 문제로 인해 발생하는 데이터 중복 저장 문제 해결
- 트랜잭션의 격리 수준을 높여 해결
- 하지만 최선의 방법은 아닌듯
> [Refactor] 약국 스크랩 동시성 문제 해결

- src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/KoreanMedicineConverter.java
> ref : \n 삭제

- src/main/java/com/pharmquest/pharmquest/domain/medicine/converter/MedicineConverter.java
> ref : 미국 usa로 변경

- src/main/java/com/pharmquest/pharmquest/domain/post/converter/PostCommentConverter.java
- src/main/java/com/pharmquest/pharmquest/domain/post/repository/comment/CommentLikeRepository.java
- src/main/java/com/pharmquest/pharmquest/domain/post/service/post/PostCommandServiceImpl.java
> [Refactor] 게시글 오류 해결
